version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: adamchleb-radicale_1
      APP_PORT: 80

  server:
    image: cupcakearmy/radicale:1
    restart: unless-stopped
    volumes: 
      - ${APP_DATA_DIR}/adamchleb-radicale/data:/data